[WIP] Initial draft for more elaborate output
svdimchenko/ski-lint pull request #2
Opened 2024-08-27 17:55 UTC by MartenBE

This is the first draft, but is still a work in progress. I hope to add color support in the next commit. At the end, I'll squash all commits is it is OK to merge.

Current preview:

![image](https://github.com/user-attachments/assets/87b09a3c-da8d-486d-8380-599bb4dc68cc)

2024-08-27 21:10 UTC, MartenBE commented
I've simplified the outpu to be more in line of `prettier` etc. and to accomodate large amounts of non-ASCII chars:

![image](https://github.com/user-attachments/assets/5e247b36-6fff-41f6-a359-1e1efb144ef9)

I've also updated the tests.

2024-08-28 07:03 UTC, svdimchenko requested changes

2024-08-28 07:03 UTC, svdimchenko commented on ski_lint/__main__.py
> +from .cli import main
there is already script defined here: https://github.com/svdimchenko/ski-lint/blob/edcd5734134069bc89d96baa5a4ed74d67b54af0/pyproject.toml#L20-L20

do we really need this file ?

2024-08-28 07:03 UTC, svdimchenko commented on ski_lint/utils.py
> +    with open(filename, "r") as f:
```suggestion
    with open(filename) as f:
```
read mode is default

2024-08-28 07:06 UTC, svdimchenko commented
@MartenBE the PR looks OK to me, I've left some minor changes suggestions. Please take a look there and we are ready to go

2024-08-28 07:45 UTC, MartenBE commented on ski_lint/__main__.py
> +from .cli import main
No, I've never worked with poetry before and I didn't know this existed. I'll remove it :)

2024-08-28 07:46 UTC, MartenBE commented on ski_lint/utils.py
> +    with open(filename, "r") as f:
Ok, I'll remove it.

2024-08-28 07:48 UTC, MartenBE commented on poetry.lock
> +# This file is automatically @generated by Poetry 1.7.1 and should not be changed by hand.
1.7.1 is the current active version in the Fedora repositories. I like to install as many python commands using the repo's instead of  `pip` so that if I upgrade my system, these packages are also updated through the package manager. So at the moment, I'd like to stick to that version.

2024-08-28 09:25 UTC, svdimchenko commented on poetry.lock
> +# This file is automatically @generated by Poetry 1.7.1 and should not be changed by hand.
I see that it depends on Fedora version: https://src.fedoraproject.org/rpms/poetry. WDYT about removing `poetry.lock` file from repo at all and add it `.gitignore` then ?

2024-08-28 12:07 UTC, MartenBE commented on poetry.lock
> +# This file is automatically @generated by Poetry 1.7.1 and should not be changed by hand.
Yeah, that seems in line with https://stackoverflow.com/questions/61037557/should-i-commit-lock-file-changes-separately-what-should-i-write-for-the-commi .

2024-08-28 12:31 UTC, svdimchenko approved these changes

2024-08-28 12:34 UTC, svdimchenko commented
Hey @MartenBE! Thanks for so rapid reactions! The last thing is about PR rule:
```
The base branch requires all commits to be signed
```
so could you please squash your commits locally and push the signed commit back to this PR ?

2024-08-28 12:41 UTC, MartenBE commented
Ah, no problem, just have to figure it out how I best do that. I'm on it!

2024-08-28 13:19 UTC, MartenBE commented
It should be done.

2024-08-28 13:37 UTC, merged