feat: allow to exclude unicode chars
svdimchenko/ski-lint pull request #5
Opened 2024-09-19 20:07 UTC by MartenBE

This is a first attempt to allow for exclusion of certain characters. As I want to be able to read a list, I've opted to allow for a config file (default `.ski-lint.yml`).

E.g.:

```yml
accepted_values:
  - U+E4
  - U+2026
```

As what options we should put in the config file, args options, or both I leave up to your decision.

I've also included some tests

2024-09-19 21:40 UTC, svdimchenko requested changes
It's great idea to implement config for this library 💯 I was also thinking about that but did not find the time to implement. So thanks a lot for your contribution!

I've left some comments regarding config processing, pls take a look there.

I've also noticed that pre-commit check failed, it would be nice to fix it as well.

2024-09-19 21:40 UTC, svdimchenko commented on ski_lint/cli.py
> +def get_config(filename: str) -> dict[str, Any]:
WDYT about using dataclass or pydantic model for config instead of plain dict ?
here are some useful libraries which can be helpful:
- https://pypi.org/project/yamldataclassconfig/
- https://pypi.org/project/pydantic-settings-yaml/

2024-09-19 21:40 UTC, svdimchenko commented on ski_lint/cli.py
> +def run(*filenames: str, check: bool = False, context_width: int, accepted_chars: list[str] = []) -> int:
I suppose it would be easier to extend the logic if needed if we pass full `config` object instead config's every specific value. Does it make sense ?

2024-09-19 21:40 UTC, svdimchenko commented on ski_lint/cli.py
> +            return 1
```suggestion
    if has_non_ascii_files and check:
        return 1
```
won't such construction work ? I seems a bit easier to read to me

2024-09-20 20:37 UTC, MartenBE commented on ski_lint/cli.py
> +            return 1
If you format it like that the check-ok log will also be printed if you have ascii errors, but the check flag is not set. Let me see if I can program it in a more intuitive way

2024-09-20 20:38 UTC, MartenBE commented on ski_lint/cli.py
> +def run(*filenames: str, check: bool = False, context_width: int, accepted_chars: list[str] = []) -> int:
Yes, this should be better

2024-09-20 20:38 UTC, MartenBE commented on ski_lint/cli.py
> +def get_config(filename: str) -> dict[str, Any]:
Pydantic seems interesting, I'll take a look at that!

2024-10-01 20:45 UTC, svdimchenko commented
hi there @MartenBE ! I've merged your previous PR, so if you are still interested in config implementation, you can resolve conflicst and continue your work on this feature.

2024-10-01 20:48 UTC, MartenBE commented
Ok! I am looking to use [pydantic-settings](https://github.com/pydantic/pydantic-settings), but am waiting for more clarification if it is usable for this use case (https://github.com/pydantic/pydantic-settings/issues/430)

2024-10-01 21:09 UTC, svdimchenko commented
> Ok! I am looking to use [pydantic-settings](https://github.com/pydantic/pydantic-settings), but am waiting for more clarification if it is usable for this use case ([pydantic/pydantic-settings#430](https://github.com/pydantic/pydantic-settings/issues/430))

one more option we can use is the combination of [python-fire](https://github.com/google/python-fire) for easy cli arguments management and just usual pydantic model for config. In this case you can manage all the settings in required way.

Python-fire can replase argparse for a very elegant way, I've tried it in some projects and it seems rather interesting to me.

2024-10-03 14:51 UTC, MartenBE commented
I've made a working version using OmegaConf. Unfortunately, I can't squash/sign my commits due to the merging of main

2024-10-03 20:43 UTC, svdimchenko requested changes
many thanks for such improvements with configuration parsing. I do like your idea with OmegaConf (I did not use it before).
I've left some comments, pls take a look there.

2024-10-03 20:43 UTC, svdimchenko commented on .markdownlint.yaml
> +MD013: false
I don't think we should disable this rule

2024-10-03 20:43 UTC, svdimchenko commented on .markdownlint.yaml
> -  code_blocks: true
it makes sense to disable MD013 for code blocks

2024-10-03 20:43 UTC, svdimchenko commented on ski_lint/cli.py
> +    ap.add_argument("--config-file", type=str, help="path to config file")
```suggestion
    ap.add_argument("-w", "--context-width", type=int, help="width of the context of the non-ASCII line")
    ap.add_argument("-c", "--config-file", type=str, help="path to config file")
```
I beliewe we should add shortened flags which will make the CLI run easier

2024-10-03 20:43 UTC, svdimchenko commented on ski_lint/cli.py
> +    try:
I would ask you to split this try...except into following 2 parts:
```
config = get_config(...). # which may contain config parsing logic
sys.exit(run(config))  # actual cli run
```

such approach will keep the main function short and strutured. Does it make sense ?

2024-10-03 20:43 UTC, svdimchenko commented on ski_lint/cli.py
> +    except ValidationError as e:
it would be nice to cover configuration parsing method with unit tests

2024-10-03 20:45 UTC, svdimchenko commented
> I can't squash/sign my commits

@MartenBE it's not a big problem, we can squash them on merge stage

2024-11-20 20:33 UTC, svdimchenko approved these changes
awesome job done 💯

2024-11-20 20:36 UTC, merged

2024-11-20 21:59 UTC, MartenBE commented
@svdimchenko I am sorry, I forgot to remove some print statements. I've added a new commit to clean this up

2024-11-20 23:02 UTC, svdimchenko commented
> @svdimchenko I am sorry, I forgot to remove some print statements: [MartenBE@89019f1](https://github.com/MartenBE/ski-lint/commit/89019f1802d97e98d81711c0783a72970afecbe8)

I've refactored a bit + applied ruff which will not allow such print statements (not only them 😄 ) in future. 
- https://github.com/svdimchenko/ski-lint/pull/6
- https://pypi.org/project/ski-lint/0.3.0/